#!/usr/bin/env python3
"""
Text to Python Conversion
Generated: 2026-06-03T18:40:40.435Z
Total Lines: 201
"""

def process_text():
    """
    Process and analyze text data
    Returns: dictionary with text data and metadata
    """
    text_lines = [
    "import json",
    "import os",
    "import random",
    "import time",
    "from openai import OpenAI",
    "# БЕЗОПАСНОСТЬ: Ключ теперь берется из секретов системы/GitHub",
    "# Чтобы запустить на ПК: укажите переменную окружения OPENROUTER_API_KEY",
    "# Чтобы запустить на GitHub Actions: добавьте этот ключ в Repository Secrets",
    "OPENROUTER_API_KEY = os.getenv(\"OPENROUTER_API_KEY\"), \"Ваш_запасной_ключ_если_запуск_локально\")",
    "# Актуальная бесплатная модель от Meta (работает стабильно)",
    "MODEL = \"meta-llama/llama-3-8b-instruct:free\"",
    "client = OpenAI(",
    "    api_key=OPENROUTER_API_KEY,",
    "    base_url=\"https://openrouter.ai/api/v1\",",
    ")",
    "# Параметры нашего любимого питомца",
    "hunger = 50",
    "happiness = 50",
    "energy = 50",
    "last_action_time = time.time()",
    "pet_alive = True",
    "inventory = [\"apple\", \"toy\", \"medicine\"]",
    "def show_inventory():",
    "    \"\"\"Показывает, какие вкусняшки и игрушки есть в рюкзачке.\"\"\"",
    "    if not inventory:",
    "        print(\"\\n🎒 Ой, твой рюкзачок пуст! Надо найти что-нибудь интересное.\")",
    "    else:",
    "        print(\"\\n🎒 Давай заглянем в твой рюкзачок:\")",
    "        translations = {\"apple\": \"🍏 Вкусное яблочко\", \"toy\": \"🧸 Плюшевый мишка\", \"medicine\": \"💊 Волшебная витаминка\"}",
    "        for index, item in enumerate(inventory, 1):",
    "            name_ru = translations.get(item, item)",
    "            print(f\"  {index}. {name_ru} ({item})\")",
    "def use_item(item_name):",
    "    \"\"\"Применяет предмет из рюкзачка.\"\"\"",
    "    global hunger, happiness, energy, inventory",
    "    if item_name not in inventory:",
    "        print(f\"\\n❌ Ой-ой! Предмета '{item_name}' нет в твоем рюкзачке.\")",
    "        return",
    "    if item_name == \"apple\":",
    "        hunger = max(0, hunger - 15)",
    "        print(\"\\n🍏 Хрум-хрум! Питомцу очень понравилось яблочко! Животик сыт.\")",
    "    elif item_name == \"medicine\":",
    "        energy = min(100, energy + 20)",
    "        happiness = min(100, happiness + 10)",
    "        print(\"\\n💊 Ура! Волшебная витаминка подействовала! Сил стало больше!\")",
    "    elif item_name == \"toy\":",
    "        happiness = min(100, happiness + 20)",
    "        energy = max(0, energy - 10)",
    "        print(\"\\n🧸 Питомцу так весело играть с мишкой! Радость взлетела до небес!\")",
    "    else:",
    "        print(f\"\\n❓ Хм, мы пока не знаем, как играть с {item_name}.\")",
    "        return",
    "    inventory.remove(item_name)",
    "def interpred_width_llm(user_command):",
    "    \"\"\"Помощник-ИИ распознает команды через бесплатную модель.\"\"\"",
    "    prompt = f\"\"\"",
    "Ты — добрый помощник в детской игре Тамагочи.",
    "Проанализируй команду ребенка и верни ТОЛЬКО одну из этих строчек:",
    "feed, play, pet, delete, toilet, inventory, use <название_предмета>.",
    "Правила:",
    "- feed — если хотят покормить",
    "- play — если хотят поиграть",
    "- pet — если хотят погладить",
    "- delete — если просят сбросить прогресс",
    "- toilet — если нужно сходить на горшок",
    "- inventory — если спрашивают про рюкзак",
    "- use <название> — если хотят применить вещь (например: \"дай яблоко\" -> use apple)",
    "Команда ребенка: \"{user_command}\"",
    "Твой ответ (строго одно слово или команда use):",
    "\"\"\"",
    "    try:",
    "        response = client.chat.completions.create(",
    "            model=MODEL,",
    "            messages=[",
    "                {\"role\": \"system\", \"content\": \"Ты милый детский игровой контроллер.\"},",
    "                {\"role\": \"user\", \"content\": prompt},",
    "            ],",
    "            temperature=0.2,",
    "            timeout=7.0  # Защита от мертвых зависаний сети",
    "        )",
    "        return response.choices[0].message.content.strip().lower()",
    "    except Exception:",
    "        return \"unknown\"",
    "def get_random_event_from_llm():",
    "    \"\"\"Получает случайное событие в формате JSON.\"\"\"",
    "    prompt = \"\"\"",
    "    Придумай одно забавное или милое случайное событие для питомца Тамагочи.",
    "    Верни ответ СТРОГО в формате JSON-объекта (без разметки markdown, без слов json и без тройных кавычек).",
    "    Структура:",
    "    {\"description\": \"текст события на русском\", \"effect\": {\"hunger\": 0, \"happiness\": 0, \"energy\": 0}}",
    "    \"\"\"",
    "    try:",
    "        response = client.chat.completions.create(",
    "            model=MODEL,",
    "            messages=[{\"role\": \"user\", \"content\": prompt}],",
    "            temperature=0.8,",
    "            timeout=7.0",
    "        )",
    "        raw_content = response.choices[0].message.content.strip()",
    "        if raw_content.startswith(\"```\"):",
    "            raw_content = raw_content.strip(\"```\").strip(\"json\").strip()",
    "        return json.loads(raw_content)",
    "    except Exception:",
    "        return {",
    "            \"description\": \"✨ Питомец нашел блестящую пуговицу и прыгает от радости!\",",
    "            \"effect\": {\"happiness\": 15, \"energy\": -5}",
    "        }",
    "def handle_random_event():",
    "    \"\"\"Показывает событие ребенку.\"\"\"",
    "    global hunger, happiness, energy",
    "    print(\"\\n🎉 Ой, смотри! Что-то происходит...\")",
    "    time.sleep(1)",
    "    event = get_random_event_from_llm()",
    "    print(f\"📢 {event['description']}\")",
    "    effects = event.get(\"effect\", {})",
    "    if \"hunger\" in effects:",
    "        hunger = max(0, min(100, hunger + effects[\"hunger\"]))",
    "    if \"happiness\" in effects:",
    "        happiness = max(0, min(100, happiness + effects[\"happiness\"]))",
    "    if \"energy\" in effects:",
    "        energy = max(0, min(100, energy + effects[\"energy\"]))",
    "def update_states():",
    "    \"\"\"Обновление жизненных показателей со временем.\"\"\"",
    "    global pet_alive, happiness, energy, hunger, last_action_time",
    "    now = time.time()",
    "    elapsed = now - last_action_time",
    "    if elapsed >= 5:",
    "        decrement = int(elapsed // 5)",
    "        hunger = min(100, hunger + decrement * 4)",
    "        happiness = max(0, happiness - decrement * 3)",
    "        energy = max(0, energy - decrement * 2)",
    "        last_action_time = now",
    "        if hunger >= 100 or happiness <= 0 or energy <= 0:",
    "            pet_alive = False",
    "def print_status():",
    "    \"\"\"Отображение состояния в консоли.\"\"\"",
    "    print(\"\\n\" + \"✨\" * 15)",
    "    print(\"🐾 Твой любимый Тамагочи:\")",
    "    print(f\"🥣 Животик (Голод): {hunger}/100\")",
    "    print(f\"💖 Радость:        {happiness}/100\")",
    "    print(f\"⚡ Силы (Энергия):  {energy}/100\")",
    "    visible_items = inventory[:3]",
    "    items_line = \", \".join(visible_items) if visible_items else \"пусто\"",
    "    if len(inventory) > 3:",
    "        items_line += f\" ... и еще {len(inventory) - 3} шт.\"",
    "    print(f\"🎒 В рюкзачке сейчас: {items_line}\")",
    "    print(\"✨\" * 15)",
    "def main():",
    "    global hunger, happiness, energy, pet_alive, inventory",
    "    print(\"👋 Привет, дружок! Добро пожаловать в мир твоего карманного друга!\")",
    "    while pet_alive:",
    "        update_states()",
    "        if not pet_alive:",
    "            break",
    "        print_status()",
    "        user_input = input(\"\\n✍️ Напиши, что ты хочешь сделать (или 'выход'): \").strip()",
    "        if user_input.lower() in ('выход', 'exit', 'quit'):",
    "            print(\"\\n👋 Пока-пока!\")",
    "            break",
    "        if not user_input:",
    "            continue",
    "        action = interpred_width_llm(user_input)",
    "        if action == \"feed\":",
    "            hunger = max(0, hunger - 20)",
    "            print(\"\\n🍼 Ням-ням-ням! Как вкусно!\")",
    "        elif action == \"play\":",
    "            happiness = min(100, happiness + 15)",
    "            energy = max(0, energy - 15)",
    "            hunger = min(100, hunger + 10)",
    "            print(\"\\n⚽ Ура, играем в мячик!\")",
    "        elif action == \"pet\":",
    "            happiness = min(100, happiness + 10)",
    "            print(\"\\n🥰 Питомец ласково зажмурился.\")",
    "        elif action == \"delete\":",
    "            hunger = 50",
    "            happiness = 50",
    "            energy = 50",
    "            inventory = [\"apple\", \"toy\", \"medicine\"]",
    "            print(\"\\n🌟 Наш Тамагочи переродился!\")",
    "        elif action == \"toilet\":",
    "            hunger = max(0, hunger - 10)",
    "            happiness = max(0, happiness - 5)",
    "            energy = max(0, energy - 5)",
    "            print(\"\\n🚽 Буль-буль! Мы сходили на горшочек.\")",
    "        elif action == \"inventory\":",
    "            show_inventory()",
    "            choice = input(",
    "                \"\\n💭 Напиши название предмета, чтобы использовать (или Enter для закрытия): \").strip().lower()",
    "            if choice:",
    "                use_item(choice)",
    "        elif action.startswith(\"use \"):",
    "            item_name = action.split(\" \", 1)[1]",
    "            use_item(item_name)",
    "        else:",
    "            print(\"\\n🤔 Питомец не совсем понял тебя. Попробуй сказать проще!\")",
    "            continue",
    "        handle_random_event()",
    "    if not pet_alive:",
    "        print(\"\\n😢 Малыш слишком устал или проголодался и уснул глубоким сном.\")",
    "if __name__ == \"__main__\":",
    "    main()"
    ]
    
    # Calculate metadata
    metadata = {
        'total_lines': 201,
        'total_characters': 8199,
        'total_words': 889,
        'created_at': '2026-06-03T18:40:40.436Z',
        'version': '1.0'
    }
    
    # Calculate statistics
    line_lengths = [len(line) for line in text_lines]
    statistics = {
        'average_line_length': sum(line_lengths) // len(line_lengths) if line_lengths else 0,
        'longest_line': max(line_lengths) if line_lengths else 0,
        'shortest_line': min(line_lengths) if line_lengths else 0,
        'empty_lines': 48
    }
    
    return {
        'lines': text_lines,
        'metadata': metadata,
        'statistics': statistics
    }

def display_text(data):
    """Display text data with metadata"""
    print("Metadata:")
    for key, value in data['metadata'].items():
        print(f"  {key}: {value}")
    
    print("\nStatistics:")
    for key, value in data['statistics'].items():
        print(f"  {key}: {value}")
    
    print("\nText Lines:")
    for i, line in enumerate(data['lines'], 1):
        print(f"Line {i}: {line}")

if __name__ == "__main__":
    data = process_text()
    display_text(data)